In [2]:
import numpy as np

In [3]:
zero_array = np.zeros( (2,3) )
zero_array

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [4]:
one_array = np.ones( (2,3) )
one_array

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [5]:
empty_array = np.empty( (2,3) )
empty_array

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [6]:
random_array = np.random.random( (2,3) )
random_array

array([[ 0.57115391,  0.74480455,  0.35287342],
       [ 0.83514607,  0.85529255,  0.4426679 ]])

In [7]:
foo = [[1,2,3], [4,5,6]]
my_array = np.array(foo)
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
range_array1 = np.arange(1,7).reshape( (2,3) )
range_array1

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
range_array2 = range_array1.reshape( (3,2) )
range_array2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
# The original array doesn't change
range_array1

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
# When you use reshape(...) the total number of things in the array must stay the same.
range_array1.reshape( (3,3) )

ValueError: total size of new array must be unchanged

In [12]:
square_array = np.arange(1, 10).reshape((3,3))
square_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
range_array1

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
range_array1[0,1]

2

In [15]:
range_array1[1, 0:2]

array([4, 5])

In [16]:
range_array1[1, 1:3]

array([5, 6])

In [17]:
range_array1[:, 0:3:2]  # skip the middle column

array([[1, 3],
       [4, 6]])

In [18]:
# Also like python lists, you can assign values to specific positions, or
# ranges of values to slices
square_array[0, :]

array([1, 2, 3])

In [19]:
square_array[0, :] = np.array(range(5,8))
square_array

array([[5, 6, 7],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
square_array[0, :] = 0
square_array

array([[0, 0, 0],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
square_array[0, :] = range(1, 4)
square_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
random_row = np.random.randint(1, 50, (10, 1))
random_row

array([[25],
       [27],
       [ 7],
       [ 1],
       [16],
       [33],
       [ 6],
       [22],
       [37],
       [11]])

In [23]:
# Something new to numpy arrays is indexing using an array of indices
fib_indices = np.array([1,1,2,3])
random_row[fib_indices]

array([[27],
       [27],
       [ 7],
       [ 1]])

In [24]:
bool_indices = np.array([[True, False, True],
                         [False, True, False],
                         [True, False, True]])


In [25]:
square_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
# a 1D array with the selected values
square_array[bool_indices]

array([1, 3, 5, 7, 9])

In [27]:
# It gets a little more complicated with 2D (and higher) arrays.  You need
# two index arrays for a 2D array:

In [28]:
# How does this work ???
rows = np.array( [[0,0], [2,2]] )
cols = np.array( [[0,2], [0,2]] )
square_array[rows, cols]

array([[1, 3],
       [7, 9]])

In [29]:
# How does this work ???
bool_rows = np.array( [True, False, True] )
bool_cols = np.array( [True, False, True] ) 
square_array[bool_rows, bool_cols]

array([1, 9])

In [30]:
# One useful trick is to create a boolean matrix based on some test and use
# that as an index in order to get the elements of a matrix that pass the test

In [31]:
sq_avg = np.average(square_array)
sq_avg

5.0

In [32]:
above_avg = square_array > sq_avg
above_avg

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]], dtype=bool)

In [33]:
square_array[above_avg]

array([6, 7, 8, 9])

In [34]:
# Indexing like this can also be used to assign values to elements of the
# array. This is particularly useful if you want to filter an array, say by 
# making sure that all of its values are above/below a certain threshold:

In [35]:
sq_std_dev = np.std(square_array)
sq_std_dev

2.5819888974716112

In [36]:
clamped_sq_array = np.array(square_array.copy(), dtype=float)
clamped_sq_array

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [37]:
# make a copy of squareArray that will be "clamped". It will only contain values within one standard deviation
# of the mean. Values that are too low or to high will be set to the min and max respectively. We set dtype=float 
# because sqAverage and sqStdDev are floating point numbers, and we don't want to truncate them down to integers.

In [38]:
clamped_sq_array[clamped_sq_array - sq_avg > sq_std_dev] = sq_avg + sq_std_dev
clamped_sq_array[sq_avg - clamped_sq_array > sq_std_dev] = sq_avg - sq_std_dev
clamped_sq_array

array([[ 2.4180111,  2.4180111,  3.       ],
       [ 4.       ,  5.       ,  6.       ],
       [ 7.       ,  7.5819889,  7.5819889]])

In [39]:
# Multiplying and dividing arrays by numbers does what you'd expect. It
# multiples/divides element-wise

In [40]:
square_array * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [41]:
square_array + np.ones(square_array.shape, dtype=int)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [42]:
square_array * np.arange(1, square_array.size + 1).reshape(square_array.shape)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [43]:
square_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
np.sum(square_array, axis=0)

array([12, 15, 18])

In [46]:
np.sum(square_array, axis=1)

array([ 6, 15, 24])

In [47]:
matA = np.arange(1,5).reshape((2,2))
matB = np.arange(5,9).reshape((2,2))

In [48]:
matA

array([[1, 2],
       [3, 4]])

In [49]:
matB

array([[5, 6],
       [7, 8]])

In [50]:
matA.dot(matB)

array([[19, 22],
       [43, 50]])

In [51]:
matA @ matB

array([[19, 22],
       [43, 50]])